"""One-time data migration: pull every table's rows from a v1-engine Aito
instance and push them into a v2 env as collections.

A straight row copy — no re-derivation. The schema is the repo's own
(`schema.TABLES`), the rows come from the v1 source verbatim (derived columns
and all), the target is a v2 env created via the (now v2) AitoClient. Views and
tables the repo no longer owns are skipped.

Usage (env vars):
    V1_URL   the v1 source, e.g. http://localhost:9005
    V1_KEY   its api key (may be empty for a local instance)
    V2_URL   the v2 target env, e.g. https://your-aito-host.example/db/<db>/env/<name>
    V2_KEY   the target read-write key
"""

import os
import sys

import requests

from company_ai import schema
from company_ai.aito import AitoClient


def v1_get(url: str, key: str, path: str) -> dict:
    h = {"x-api-key": key} if key else {}
    r = requests.get(f"{url}{path}", headers=h, timeout=120)
    r.raise_for_status()
    return r.json()


def v1_query(url: str, key: str, table: str) -> list[dict]:
    h = {"content-type": "application/json", **({"x-api-key": key} if key else {})}
    r = requests.post(f"{url}/api/v1/_query", json={"from": table, "limit": 1_000_000},
                      headers=h, timeout=300)
    r.raise_for_status()
    # drop Aito's computed $-fields; keep only stored columns
    return [{k: v for k, v in hit.items() if not k.startswith("$")}
            for hit in r.json()["hits"]]


# search-session telemetry: regenerated by use, and its schema evolved in the
# migration — not worth carrying old rows across.
SKIP = {"search_contexts", "search_impressions"}


def migrate(v1_url: str, v1_key: str, v2: AitoClient) -> list[tuple]:
    source = set(v1_get(v1_url, v1_key, "/api/v1/schema")["schema"])
    # migrate tables the repo still owns as tables (skip views / dropped / telemetry)
    tables = [t for t in schema.TABLES if t in source and t not in SKIP]
    report = []
    for table in tables:                     # schema.TABLES is dependency-ordered
        rows = v1_query(v1_url, v1_key, table)
        v2.delete_table(table)
        v2.create_table(table, schema.TABLES[table])
        if rows:
            v2.upload_batch(table, rows)
        got = v2.count(table)
        report.append((table, len(rows), got))
        print(f"  {table:22} v1={len(rows):>5}  ->  v2={got:>5}  {'ok' if got == len(rows) else 'MISMATCH'}")
    return report


if __name__ == "__main__":
    v1_url = os.environ["V1_URL"].rstrip("/")
    v1_key = os.environ.get("V1_KEY", "")
    v2 = AitoClient(os.environ["V2_URL"].rstrip("/"), os.environ["V2_KEY"])
    print(f"pull {v1_url} (v1) -> push {v2.base_url} (v2 collections)")
    report = migrate(v1_url, v1_key, v2)
    ok = all(a == b for _, a, b in report)
    print(f"\n{len(report)} tables, {sum(a for _, a, _ in report)} rows; all counts match: {ok}")
    sys.exit(0 if ok else 1)
